### ISSUE TITLE
Unexpected error occurred: Error instantiating bean of type  [io.micronaut.security.authentication.Authenticator]

### ISSUE THREAD

**Issue by davRg** [micronaut-guides/micronaut-oauth2-oidc-google#6]
When you tried to run the example, a exception is thrown

```
15:18:49.875 [nioEventLoopGroup-1-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Error instantiating bean of type  [io.micronaut.security.authentication.Authenticator]
> :run
Message: Bean Factory [Definition: io.micronaut.security.oauth2.endpoint.token.request.password.PasswordGrantFactory] returned null
Path Taken: new SecurityFilter(Collection securityRules,[Collection authenticationFetchers],SecurityConfiguration securityConfiguration) --> new BasicAuthAuthenticationFetcher([Authenticator authenticator],BasicAuthAuthenticationConfiguration configuration) --> new Authenticator([Collection authenticationProviders],SecurityConfiguration securityConfiguration)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.security.authentication.Authenticator]

Message: Bean Factory [Definition: io.micronaut.security.oauth2.endpoint.token.request.password.PasswordGrantFactory] returned null
Path Taken: new SecurityFilter(Collection securityRules,[Collection authenticationFetchers],SecurityConfiguration securityConfiguration) --> new BasicAuthAuthenticationFetcher([Authenticator authenticator],BasicAuthAuthenticationConfiguration configuration) --> new Authenticator([Collection authenticationProviders],SecurityConfiguration securityConfiguration)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1897)
        at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2950)
        at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2861)
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1039)
```

**Comment by sdelamo** [comment]
I've just updated the guide to 2.0.0.RC1. 

You could clone the repo and type: 

```
% export OAUTH_CLIENT_ID=YYY
% export OAUTH_CLIENT_SECRET=XXXX
% ./gradlew complete:run  
```

and login with your google account.
